name: CI

on:
  push:
    branches:
      - working
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        ports:
          - 5432:5432
      redis:
        image: redis:6
        env:
          REDIS_PASSWORD: ${{ secrets.TEST_REDIS_PASSWORD }}
        options: >-
          --health-cmd="redis-cli -a $${REDIS_PASSWORD} ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.4

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      env:
        DB_HOST: ${{ secrets.TEST_DB_HOST }}
        DB_PORT: ${{ secrets.TEST_DB_PORT }}
        DB_USER: ${{ secrets.TEST_DB_USER }}
        DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        DB_NAME: ${{ secrets.TEST_DB_NAME }}
        REDIS_HOST: ${{ secrets.TEST_REDIS_HOST }}
        REDIS_PORT: ${{ secrets.TEST_REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.TEST_REDIS_PASSWORD }}
        REDIS_DB: ${{ secrets.TEST_REDIS_DB }}
      run: go test ./...

    - name: Build the application
      run: go build -o main .
